version: '3'
services:
  redis:
    image: redis:5-alpine
    restart: always
    ports:
    - 6379:6379
    command:
    - --protected-mode
    - 'no'

  mongo:
    image: mongo:4-xenial
    restart: always
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: USMxfUicr9QUsx3kLQ
    volumes:
    - data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: USMxfUicr9QUsx3kLQ

volumes:
  data:
